### ISSUE TITLE
biolink-model.owl.ttl is moving locations on github

### ISSUE THREAD

**Issue by sierra-moxon** [MaastrichtU-IDS/knowledge-collaboratory#14]
Please note: https://raw.githubusercontent.com/biolink/biolink-model/master/biolink-model.owl.ttl will no longer be available at this path in biolink 4.0.0.

Instead, it will be here: https://raw.githubusercontent.com/biolink/biolink-model/master/project/owl/biolink_model.owl.ttl 

or via w3id here (this is still the same path/URI as pre-4.0.0): https://w3id.org/biolink/biolink-model.owl.ttl

https://github.com/MaastrichtU-IDS/knowledge-collaboratory/blob/8263d69e7b8e485b0aff7e88a3a7aed3cceaa253/backend/app/api/nanopub.py#L35

**Comment by micheldumontier** [comment]
This is addressed in codebase.
