### ISSUE TITLE
Sometimes slow responsiveness of /meta_knowledge_graph endpoint

### ISSUE THREAD

**Issue by CaseyTa** [MaastrichtU-IDS/knowledge-collaboratory#16]
The `/meta_knowledge_graph` endpoint sometimes responds in <5 seconds and sometimes takes >30 seconds to respond. Since this endpoint is queried often in Translator ecosystem, it would be good to improve the responsiveness of this endpoint, potentially by adding caching. 

Related issue in Translator Feedback repo for history of issues experienced by ARA teams:
https://github.com/NCATSTranslator/Feedback/issues/593

**Comment by CaseyTa** [comment]
@isbluis reporting that `/meta_knowledge_graph` is still having problems in dev and CI. 
https://github.com/NCATSTranslator/Feedback/issues/593#issuecomment-2143129692

I'm seeing 500 internal server errors in all environments right now

@micheldumontier Is there anyone who can look into this?

**Comment by micheldumontier** [comment]
This was solved with a change in the nanopub  SPARQL URL  [ac7e184](https://github.com/MaastrichtU-IDS/knowledge-collaboratory/commit/ac7e1843685b8cc8f114dc246f6b4afb505d3abf)
