### ISSUE TITLE
JSON Decode exception

### ISSUE THREAD

**Issue by ensaremirerol** [MaastrichtU-IDS/knowledge-collaboratory#20]
Hi @micheldumontier,

Problem happens at /backend/app/trapi/reasonerapi_parser.py:375

https://github.com/MaastrichtU-IDS/knowledge-collaboratory/blob/ac7e1843685b8cc8f114dc246f6b4afb505d3abf/backend/app/trapi/reasonerapi_parser.py#L375

Probably receives some malformed or incomplete json from the endpoint

I can debug it if you want but you need to give me some example requests to work on.

**Comment by micheldumontier** [comment]
the problem here was that the nanopublication wrapper docker was failing to process the get_np_users() request. the logs indicated that the process was immediately getting killed. we restarted the container and it solved the problem. docker voodoo magic problem...
